#
# Module manifest for module 'QRCodes'
#
# Generated by: Chris Duck (gpduck@whatsupduck.net)
#
# Generated on: 5/6/2012
#

@{

# Script module or binary module file associated with this manifest
ModuleToProcess = 'QRCodes.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'ab86e4cb-f62f-4bca-82ae-bfcfa8ab045c'

# Author of this module
Author = 'Chris Duck (gpduck@whatsupduck.net)'

# Company or vendor of this module
CompanyName = ''

# Copyright statement for this module
Copyright = 'Chris Duck 2012'

# Description of the functionality provided by this module
Description = 'PowerShell module that uses the Google ZXing.Net library to generate QRCodes.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = ''

# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @('ZXing.Net\lib\net40\zxing.dll')

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in ModuleToProcess
NestedModules = @()

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
FileList = @()

# Private data to pass to the module specified in ModuleToProcess
PrivateData = ''

}

